[2022-01-27 14:47:31,393] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: cgi_40.load_data_source 2022-01-27T14:47:30.349603+00:00 [queued]>
[2022-01-27 14:47:31,401] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: cgi_40.load_data_source 2022-01-27T14:47:30.349603+00:00 [queued]>
[2022-01-27 14:47:31,401] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2022-01-27 14:47:31,401] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2022-01-27 14:47:31,401] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2022-01-27 14:47:31,410] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): load_data_source> on 2022-01-27T14:47:30.349603+00:00
[2022-01-27 14:47:31,418] {standard_task_runner.py:52} INFO - Started process 76 to run task
[2022-01-27 14:47:31,423] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'cgi_40', 'load_data_source', '2022-01-27T14:47:30.349603+00:00', '--job-id', '10', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/cgi40_dag.py', '--cfg-path', '/tmp/tmpb0pkble7', '--error-file', '/tmp/tmpl95jra71']
[2022-01-27 14:47:31,423] {standard_task_runner.py:77} INFO - Job 10: Subtask load_data_source
[2022-01-27 14:47:31,452] {logging_mixin.py:104} INFO - Running <TaskInstance: cgi_40.load_data_source 2022-01-27T14:47:30.349603+00:00 [running]> on host bb053c5f0074
[2022-01-27 14:47:31,493] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=oulespaul@gmail.com
AIRFLOW_CTX_DAG_OWNER=ETDA
AIRFLOW_CTX_DAG_ID=cgi_40
AIRFLOW_CTX_TASK_ID=load_data_source
AIRFLOW_CTX_EXECUTION_DATE=2022-01-27T14:47:30.349603+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-01-27T14:47:30.349603+00:00
[2022-01-27 14:47:31,493] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2022-01-27 14:47:31,494] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'cd /dags && ls']
[2022-01-27 14:47:31,502] {subprocess.py:75} INFO - Output:
[2022-01-27 14:47:31,504] {subprocess.py:79} INFO - bash: line 0: cd: /dags: No such file or directory
[2022-01-27 14:47:31,505] {subprocess.py:83} INFO - Command exited with return code 1
[2022-01-27 14:47:31,512] {taskinstance.py:1481} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1137, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2022-01-27 14:47:31,514] {taskinstance.py:1531} INFO - Marking task as FAILED. dag_id=cgi_40, task_id=load_data_source, execution_date=20220127T144730, start_date=20220127T144731, end_date=20220127T144731
[2022-01-27 14:47:31,552] {local_task_job.py:151} INFO - Task exited with return code 1
